title: "Risk-Averse Zero-Order Trajectory Optimization"
description: Supplementary Website

username: 
email: sample.efficient.cross.entropy@gmail.com

authors: "Marin Vlastelica, Sebastian Blaes, Cristina Pinneri, Georg Martius"
